server:
  port: 8084
spring:
  application:
    name: AuthenticationMs
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${random.value}
  config:
    import: optional:configserver:${URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: GDHJKGDFFfjsdgfsdfdfdttyyuoyuoiupupiupiopop6796979
  expiration: 3600000
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always






