spring:
  application:
    name: Order-service
  datasource:
    url: ${URL_ORDERS}
    username: ${USERNAME_ORDERS}
    password: ${PASSWORD_ORDERS}
    driver-class-name: ${DRIVER_CLASS_NAME_ORDERS}