server:
  port: 8080
spring:
  application:
    name: Gateway
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        enabled: true
    config:
      discovery:
        enabled: true
        service-id: config-server
  config:
    import: optional:configserver:"${SPRING_CONFIG_IMPORT}"
management:
  endpoints:
    web:
      exposure:
        include: "*"


