spring:
  application:
    name: books-service
  datasource:
    url: ${URL_BOOKS}
    username: ${USERNAME_BOOKS}
    password: ${PASSWORD_BOOKS}
    driver-class-name: ${DRIVER_CLASS_NAME_BOOKS}
  data:
    mongodb:
      uri: ${MONGODB_URI_BOOKS}

